language: python
branches:
  only:
    - master
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -q -r requirements.txt
  - pip install -q .
# command to run tests
script: pytest 
