language: python
branches:
  only:
    - master
dist: xenial
python:
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install python-dev graphviz libgraphviz-dev pkg-config
install:
  - pip install -q -r requirements.txt
  - pip install -q .
# command to run tests
script: pytest 
deploy:
  skip_cleanup: true
