language: python
branches:
  only:
    - master
dist: xenial
python:
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install r-cran-dplyr
install:
  - pip install -v -r requirements.txt
  - pip install -v .
# command to run tests
script: pytest
addons:
  apt:
    packages:
      - python-dev
      - graphviz
      - libgraphviz-dev
      - pkg-config
      - r-base